// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOtX1CpH5iZGQr7EoACwSSiRT1gwvr3M',
    appId: '1:299164683266:web:be6d8ccf56e1582e442b1b',
    messagingSenderId: '299164683266',
    projectId: 'uzum-market-7de6d',
    authDomain: 'uzum-market-7de6d.firebaseapp.com',
    storageBucket: 'uzum-market-7de6d.firebasestorage.app',
    measurementId: 'G-M13GF8RH1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uWbAdeAF4oHJBcTjrcMFPpR7SN9n7HY',
    appId: '1:299164683266:android:ff4a161a2fb2d3e4442b1b',
    messagingSenderId: '299164683266',
    projectId: 'uzum-market-7de6d',
    storageBucket: 'uzum-market-7de6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7y0-Q4dTUZAjnDiisN0y1zRZFgf4Ksk',
    appId: '1:299164683266:ios:4e7778571cf0d4b2442b1b',
    messagingSenderId: '299164683266',
    projectId: 'uzum-market-7de6d',
    storageBucket: 'uzum-market-7de6d.firebasestorage.app',
    iosBundleId: 'uz.sardor.uzumMarket',
  );
}
